nodejs:
  applicationPort: 3000
  aadIdentityName: response
  ingressHost: response.platform.hmcts.net
  environment:
    image: 'hmctspublic.azurecr.io/incident/response:latest'
  keyVaults:
    response:
      secrets:
        - slack-signing-secret
        - slack-bot-token
